### ISSUE TITLE
The Exe Should be Tiny

### ISSUE THREAD

**Issue by LesFerch** [medic17/win11ie#1]
The provided Exe is a whopping 55MB. I compiled the code, targeted to .Net Framework 4.8, and the Exe was only 7KB.

My final [LaunchIE.exe](https://lesferch.github.io/LaunchIE/) is 98K after adding icons and a signing the code.

**Comment by medic17** [comment]
> The provided Exe is a whopping 55MB. I compiled the code, targeted to .Net Framework 4.8, and the Exe was only 7KB.
> 
> My final [LaunchIE.exe](https://lesferch.github.io/LaunchIE/) is 98K after adding icons and a signing the code.

True. I included the full runtime for convinance in the release file as this project targets envirments that may not have the runtime installed. I did not want to setup an installer for this, so I made the decision to include the runtime. Was this the only cause for the bloat?
